# Generated by Django 3.2.6 on 2022-08-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_trans', models.CharField(max_length=254)),
                ('magic_def', models.CharField(max_length=254)),
                ('example_card_1', models.CharField(blank=True, max_length=254, null=True)),
                ('example_card_2', models.CharField(blank=True, max_length=254, null=True)),
                ('german_trans', models.CharField(blank=True, max_length=254, null=True)),
                ('japanese_trans', models.CharField(blank=True, max_length=254, null=True)),
                ('furigana', models.CharField(blank=True, max_length=254, null=True)),
                ('romaji', models.CharField(blank=True, max_length=254, null=True)),
                ('french_trans', models.CharField(blank=True, max_length=254, null=True)),
                ('lit_trans_list', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
